"""Retrieval evaluation: python -m app.kb.evaluate  ->  reports/retrieval_eval.md + .json

Verdicts
  correct            top-1 relevant hit is an expected record (or, for out-of-scope, nothing passes the gate)
  partially correct  an expected record is in the top-3 but not first
  incorrect          otherwise
"""
from __future__ import annotations

import json
import time
from collections import Counter

from app.config import DATA_DIR, REPORTS_DIR
from app.kb.store import KnowledgeBase, tokenize


def _matches(hit: dict, expected: list[dict]) -> bool:
    for e in expected:
        if e["source_id"] in ("*", hit["source"]["source_id"]) and e["section"].lower() in hit["title"].lower():
            return True
    return False


def evaluate() -> list[dict]:
    queries = json.loads((DATA_DIR / "eval" / "retrieval_queries.json").read_text(encoding="utf-8"))
    results = []
    for q in queries:
        kb = KnowledgeBase.get(q["collection"])
        t0 = time.perf_counter()
        hits = kb.search(q["question"], k=3)
        ms = (time.perf_counter() - t0) * 1000
        relevant = [h for h in hits if h["relevant"]]
        top = hits[0] if hits else None
        if not q["expected"]:
            verdict = "correct" if not relevant else "incorrect"
            why = ("No record passed the relevance gate, so the agent says the information is unavailable."
                   if not relevant else f"Gate wrongly accepted '{relevant[0]['title']}'.")
        else:
            ranks = [i for i, h in enumerate(hits) if _matches(h, q["expected"])]
            if ranks and ranks[0] == 0 and top["relevant"]:
                verdict = "correct"
            elif ranks:
                verdict = "partially correct"
            else:
                verdict = "incorrect"
            shared = sorted(set(tokenize(q["question"])) & set(tokenize(top["title"] + " " + top["content"]))) if top else []
            if verdict == "correct":
                why = f"Top hit is the expected section; shared terms: {', '.join(shared[:6]) or 'semantic match only'}."
            elif verdict == "partially correct":
                why = (f"Expected section ranked #{ranks[0] + 1}"
                       + ("" if top["relevant"] else " and top hit fell below the relevance gate")
                       + f"; top hit was '{top['title']}'.")
            else:
                why = f"Expected section not in top-3; top hit was '{top['title'] if top else '-'}'."
        results.append({
            **{k: q[k] for k in ("id", "collection", "type", "question")},
            "verdict": verdict, "explanation": why, "latency_ms": round(ms, 1),
            "top_hit": None if not top else {
                "record_id": top["record_id"], "title": top["title"], "content": top["content"],
                "citation": top["citation"], "scores": top["scores"], "relevant": top["relevant"]},
            "top3": [{"record_id": h["record_id"], "title": h["title"], "scores": h["scores"], "relevant": h["relevant"]}
                     for h in hits],
        })
    return results


def write_report(results: list[dict]) -> None:
    counts = Counter(r["verdict"] for r in results)
    lat = sorted(r["latency_ms"] for r in results)
    lines = [
        "# Retrieval evaluation", "",
        f"Queries: {len(results)} | correct: {counts['correct']} | partially correct: {counts['partially correct']} | "
        f"incorrect: {counts['incorrect']} | median latency: {lat[len(lat) // 2]:.0f} ms", "",
        "Generated by `python -m app.kb.evaluate`. Hybrid retrieval (dense + BM25, reciprocal-rank fusion) "
        "with a relevance gate; out-of-scope questions are correct only when nothing passes the gate.", "",
        "| ID | Type | Question | Retrieved record | Source reference | Scores (dense / bm25) | Verdict |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in results:
        t = r["top_hit"]
        rec = f"`{t['record_id']}` {t['title']}" + ("" if t["relevant"] else " *(below gate)*") if t else "-"
        lines.append(f"| {r['id']} | {r['type']} | {r['question']} | {rec} | {t['citation'] if t else '-'} | "
                     f"{t['scores']['dense']} / {t['scores']['bm25']} | **{r['verdict']}** |" if t else
                     f"| {r['id']} | {r['type']} | {r['question']} | - | - | - | **{r['verdict']}** |")
    lines += ["", "## Relevance explanations", ""]
    for r in results:
        lines.append(f"- **{r['id']}** ({r['verdict']}): {r['explanation']}")
        if r["top_hit"]:
            lines.append(f"  - Retrieved text: \"{r['top_hit']['content'][:220].replace(chr(10), ' ')}...\"")
    (REPORTS_DIR / "retrieval_eval.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (REPORTS_DIR / "retrieval_eval.json").write_text(json.dumps(results, indent=2, ensure_ascii=False), encoding="utf-8")


if __name__ == "__main__":
    res = evaluate()
    write_report(res)
    for r in res:
        t = r["top_hit"] or {}
        print(f"{r['id']} {r['verdict']:<18} {t.get('scores')} gate={t.get('relevant')} | {t.get('title')}")
    print(Counter(r["verdict"] for r in res))
