"""Run the live-insight scenarios headless and write the latency + false-positive report.

    python -m app.live.evaluate                 # replay all scenarios at real-time speed, then report
    python -m app.live.evaluate --report        # only rebuild reports/live_eval.md from saved sessions

The report pools the latest session per source, including sessions run from the dashboard (those also
carry WebSocket delivery/display latency, which a headless run cannot measure).
"""
from __future__ import annotations

import asyncio
import json
import sys

from app.config import REPORTS_DIR
from app.live.pipeline import SESSIONS_DIR, LiveSession, list_sources
from app.metrics import percentile

COMPONENTS = [("endpoint_ms", "End-pointing (speech end -> segment closed)"),
              ("asr_queue_ms", "ASR queue / rate-limit wait"),
              ("asr_ms", "ASR (Whisper, per segment)"),
              ("rules_ms", "Signal extraction - rules"),
              ("llm_ms", "Signal extraction - LLM"),
              ("nudge_ms", "Nudge control"),
              ("delivery_ms", "Delivery (WebSocket send -> rendered ack, round trip)"),
              ("e2e_emit_ms", "End-to-end: speech end -> nudge emitted"),
              ("e2e_display_ms", "End-to-end: speech end -> nudge displayed")]


async def run_all(speed: float) -> None:
    for src in list_sources():
        if src["kind"] != "scenario":
            continue
        print(f"> {src['id']} ({src['duration']} s at {speed}x)")

        async def emit(ev: dict) -> None:
            if ev["type"] == "nudge":
                n = ev["nudge"]
                print(f"   [{n['emitted_audio_t']:6.1f}s] NUDGE {n['type']}: {n['text'][:90]}  {n['timings']}")
            elif ev["type"] == "signal" and ev["suppressed"]:
                print(f"   [{ev['t']:6.1f}s] suppressed {ev['type']}: {ev['suppressed']}")
            elif ev["type"] == "error":
                print("   ERROR", ev["message"])

        summary = await LiveSession(src["id"], emit, speed=speed).run()
        print(f"   evaluation: {summary['evaluation']}")


def latest_sessions() -> list[dict]:
    latest: dict[str, dict] = {}
    for path in sorted(SESSIONS_DIR.glob("*.json")):
        s = json.loads(path.read_text(encoding="utf-8"))
        latest[s["source_id"]] = s
    return list(latest.values())


def write_report() -> None:
    sessions = latest_sessions()
    nudges = [n for s in sessions for n in s["nudges"]]
    segs = [x for s in sessions for x in s["transcript"]]
    lines = ["# Live insights: latency and false-positive report", "",
             f"Sessions: {len(sessions)} (latest per source). Nudges delivered: {len(nudges)}. "
             f"ASR segments: {len(segs)}. Generated by `python -m app.live.evaluate`.", "",
             "## End-to-end and component latency (per delivered nudge)", "",
             "| Component | P50 (ms) | P95 (ms) | n |", "|---|---|---|---|"]
    for key, label in COMPONENTS:
        vals = [n["timings"].get(key) for n in nudges]
        n = len([v for v in vals if v is not None])
        lines.append(f"| {label} | {percentile(vals, 0.5) if n else '-'} | {percentile(vals, 0.95) if n else '-'} | {n} |")
    asr = [x["asr_ms"] for x in segs]
    rtf = [x["rtf"] for x in segs]
    lines += ["", f"Transcription latency per chunk (all {len(segs)} speech segments): P50 {percentile(asr, 0.5)} ms, "
              f"P95 {percentile(asr, 0.95)} ms; real-time factor P50 {percentile(rtf, 0.5)}.",
              "Delivery/display rows are filled only by dashboard sessions (a headless run has no browser).", "",
              "## False-positive analysis", "",
              "| Source | Expected nudges | TP | FP | FN | Precision | Recall | Raw signals | Delivered | "
              "Suppressed (by reason) | Low-confidence segments filtered |",
              "|---|---|---|---|---|---|---|---|---|---|---|"]
    fp_details = []
    for s in sessions:
        ev = s.get("evaluation")
        sup = ", ".join(f"{k}: {v}" for k, v in s["suppressed_by_reason"].items()) or "-"
        if ev:
            exp = ev["true_positives"] + len(ev["false_negatives"])
            prec = "-" if ev["precision"] is None else f"{ev['precision']:.2f}"
            rec = "-" if ev["recall"] is None else f"{ev['recall']:.2f}"
            lines.append(f"| {s['source_id']} | {exp} | {ev['true_positives']} | {len(ev['false_positives'])} | "
                         f"{len(ev['false_negatives'])} | {prec} | {rec} | {s['raw_signals']} | {s['nudges_delivered']} | "
                         f"{sup} | {s['segments_filtered_low_confidence']}/{s['segments']} |")
            fp_details += [f"- `{s['source_id']}` FP **{f['type']}** at {f['t']} s: \"{f['evidence']}\"" for f in ev["false_positives"]]
            fp_details += [f"- `{s['source_id']}` FN **{f['type']}** (expected around turn {f['turn']})" for f in ev["false_negatives"]]
        else:
            lines.append(f"| {s['source_id']} | (no ground truth) | - | - | - | - | - | {s['raw_signals']} | "
                         f"{s['nudges_delivered']} | {sup} | {s['segments_filtered_low_confidence']}/{s['segments']} |")
    tp = sum(s["evaluation"]["true_positives"] for s in sessions if s.get("evaluation"))
    fp = sum(len(s["evaluation"]["false_positives"]) for s in sessions if s.get("evaluation"))
    fn = sum(len(s["evaluation"]["false_negatives"]) for s in sessions if s.get("evaluation"))
    if tp + fp:
        lines += ["", f"Overall: precision {tp / (tp + fp):.2f}, recall {tp / max(tp + fn, 1):.2f} "
                  f"(TP {tp}, FP {fp}, FN {fn}). A nudge counts as TP when its type matches an expected nudge and it is "
                  "emitted between 1 s before the evidence turn starts and 20 s after it ends; optional expectations "
                  "(acceptable but not required) count as neither TP nor FP."]
    lines += ["", "### False positives and misses", ""] + (fp_details or ["- none"])
    lines += ["", "## Delivered nudges", ""]
    for s in sessions:
        lines.append(f"**{s['source_id']}**")
        for n in s["nudges"]:
            lines.append(f"- [{n['emitted_audio_t']} s] `{n['type']}` (p{n['priority']}, conf {n['confidence']}, "
                         f"{n['source']}): {n['text']} - e2e {n['timings'].get('e2e_emit_ms')} ms")
        lines.append("")
    (REPORTS_DIR / "live_eval.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote reports/live_eval.md")


if __name__ == "__main__":
    args = sys.argv[1:]
    if "--report" not in args:
        speed = float(args[args.index("--speed") + 1]) if "--speed" in args else 1.0
        asyncio.run(run_all(speed))
    write_report()
